version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: weather_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: genesis_test_task
    ports:
      - "${DB_PORT_HOST:-5434}:${DB_PORT_CONTAINER:-5432}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-genesis_test_task}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_app_container
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=genesis_test_task
      - GMAIL_CREDENTIALS=${GMAIL_CREDENTIALS}
      - GMAIL_TOKEN=${GMAIL_TOKEN}
      - GMAIL_FROM=${GMAIL_FROM:-noreply@example.com}
      - API_KEY=${API_KEY}
volumes:
  postgres_data:
